kind: Deployment
apiVersion: apps/v1
metadata: 
  name: result-app-deploy
  labels:
    name: result-app-deloy
    app: demo-voting-app
spec:
 replicas: 1
 selector:
  matchLabels:
   name: result-app-pod
   app: demo-voting-app
 template:
  metadate:
   name: result-app-pod
   labels:
    name: result-app-pod
    app: demo-voting-app
  spec:
   containers:
    - name: resutl-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
       - containerport: 80
